### ISSUE TITLE
Space `creator` property

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Graph#14]
@johnsamuelwrites, I noticed in the workspace model a space can have a `creator` but I don't think this applies to the consensus space. The consensus space is not created by someone, but simply exists, no?

**Comment by DiegoVinasco** [comment]
In fact can any space have a creator? I think a workspace is just composed of a consensus space and an optional proposition space, there is not creator for either, they are just a part of the workspace.

**Comment by johnsamuelwrites** [comment]
@DiegoVinasco yes we need creator for space/consensus space for tracking the person(s)/institution(s) who have proposed a scenario of versions (consensus or not). For example, the creator of consensus space for a scenario of official versions will be the provider of the data (e.g., Metropole, City organizations, etc.).

**Comment by DiegoVinasco** [comment]
@johnsamuelwrites ok that makes sence. This way someone could have a workspace with only a concensus space until someone creates the proposition space and then that person or entity can be saved.
