### ISSUE TITLE
Ontology validation

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Graph#19]
We need to formalize our ontology validation evaluation plan:
- [x] Test consistency with Reasoner
- [x] [RDFValidator](https://rdfvalidator.mybluemix.net/)
- [x] [Catalogue of common pitfalls identified by OOPS](https://oops.linkeddata.es/catalogue.jsp) (replace file extensions with symbolic links)
- [ ] [FAIRness](https://github.com/agroportal/fairness)
- [x] [OWLReady2](https://bitbucket.org/jibalamy/owlready2/src/master/)

Alignments:
- ~Define alignment task: base it on the state of the art if possible (usmani, kolbe, beck, Liu)~
- ~Explore Ontology repair tools/algorithms~

**Comment by johnsamuelwrites** [comment]
Test the datasets with these tools
- [ ] [Catalogue of common pitfalls identified by OOPS](https://oops.linkeddata.es/catalogue.jsp)
- [ ] [RDFValidator](https://rdfvalidator.mybluemix.net/)
- [ ] [FAIRness](https://github.com/agroportal/fairness)
- [ ] [OWLReady2](https://bitbucket.org/jibalamy/owlready2/src/master/)

**Comment by DiegoVinasco** [comment]
Looks like we're failing miserably at FAIRness standards..

The proposed CityGML 3.0 [core ontology](https://github.com/VCityTeam/UD-Graph/blob/master/Ontologies/CityGML/3.0/core.ttl) scored 23% on the [FOOPS validator](https://foops.linkeddata.es/FAIR_validator.html). Below is a breakdown of the results:

| Ontology | Findable | Accessible | Interoperable | Reusable |
|---|---|---|---|---|
| CGML3 core | 0/9 | 1.5/3 | 3/3 | 1/9 |

Many of these issues are due to the limitations of hosting on Github. For example, we can't host a URL that can resolve into an HTML document based on an HTTP request.

For some reason, the validator is not picking up the fact we are generating SKOS documentation for all of our declared classes and properties, which would raise our reusability.

Some things we can do to improve the score are:
- register ontology uris with w3id, purl, DOI or W3C
- make ontology uris the same as their github raw content url
  - although this is technically a minor pitfall in OOPS, this is likely impossible to avoid when using Github
  - we could try storing our ontology files without a file type?
- properly add version uris
- add triple metadata! at minimum:
  - title
  - description
  - license (make sure the license declaration actually resolves for bonus points)
  - version iri
  - creator
  - author *
  - creationDate *
  - namespace URI
- declare a prefix in each ontology
- register metadata with LOV:
  - ontology prefix
  - ontology URL/URI
  - minimum metadata (same as above)
- add other metadata such as:
  - doi
  - previous version *
  - contributor *
  - publisher *
  - logo
  - backwards compatibility
  - status
  - modified
  - source
  - issued date *

\* provenance metadata: this is worth bonus point in FAIR assessments

**Comment by DiegoVinasco** [comment]
Ontologies have been moved to [dataset.liris](https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/Readme.html) server. In order to fix minor OOPS pitfall (no file extensions in URI) we can use symbolic links.

**Comment by DiegoVinasco** [comment]
Will close this issue, moved [FAIRness](https://github.com/agroportal/fairness) task to #39
