### ISSUE TITLE
SWRL rule validation

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Graph#23]
For SWRL rule validation the SWRLTab in Protege does not seem to like that we use locally scoped property naming conventions in our ontologies.

OwlReady2 seems to be ok with this however it cannot read ontologies formalized in anything but the OWL/XML syntax (our ontologies are in either turtle or OWL/RDF syntax).

Otherwise, initial tests with SWRL are promising.

Two scripts/tools need to be created:
- ~A tool for converting an ontology to OWL/XML (probably with RDFLib)~
- [x] A tool that can parse a text file (with rules) and ontologies with OwlReady2 to validate the ontology.
- [x] Create a ruleset from [[Samuel 2020]](https://hal.archives-ouvertes.fr/hal-02454953/file/article.pdf)
- [x] Test ruleset against a test dataset
- [x] Test ruleset on the GratteCiel dataset

**Comment by DiegoVinasco** [comment]
When writing rules in OwlReady2, namespace prefixes do not seem to be used. What happens when we reference two classes from different namespaces but with the same name? Which class is used in the rule?

**Comment by DiegoVinasco** [comment]
Add functionality to the script to read a text file with rules [here](https://github.com/VCityTeam/UD-Graph/commit/3de64c72e284f1e18897651548ad088b5f7f02dd). Owlready2 also seems to be working properly with namespaces now and can support more than one imported ontology.

However, it looks like RDFLib can only export knowledge graphs in RDF **FORMATS** such as turtle, n-triples, RDF/XML etc. but not other languages such as OWL/XML. So far, it looks like the fastest way to transform ontologies from RDF/XML to OWL/XML is through Protégé.

Now we just need to finish creating the workspace rules based on [Samuel 2020]

**Comment by DiegoVinasco** [comment]
Some rules may have to be updated from [Samuel 2020] to better match CityGML 3.0 and Inspire best practices.

**Comment by DiegoVinasco** [comment]
Concerning [Samuel 2020] rules:
- rule 44 could be ignored as CityGML 3.0 Versions do not have versionType attributes. Instead Versions in ConsensusSpace can be interpreted as implicitly 'existing' and Versions in PropositionSpace are implicitly 'imagined'
- concerning rule 47, I would propose the initial Version exists only in ConcensusSpace. Consequently this can be handled with OWL

**Comment by johnsamuelwrites** [comment]
* Rule 44: VersionType (Existing) or VersionTransitionType (Influence) need not be considered in the initial version. Since, they are not in CityGML 3.0, we will consider them later.
* Rule 47 corresponds to at least one common version shared between consensus space scenario and every proposition space scenario.

**Comment by DiegoVinasco** [comment]
Added a script to add timestamps to CityGML CityModel features [here](https://github.com/VCityTeam/UD-Graph/blob/rules/Transformations/DifferenceGraph-to-CityGML3/readme.md#addtimestampspy-documentation)

Tested the [datasets](/Datasets) with pellet (just the ABox), so far so good.

Next step will be to add timestamps to the workspace version and versiontransitions using the [DifferenceGraph](https://github.com/VCityTeam/UD-Graph/blob/rules/Transformations/DifferenceGraph-to-CityGML3/readme.md#differencegraph2rdfpy-documentation) script

**Comment by DiegoVinasco** [comment]
Looks like there is still a bit of work to use owlready2 for temporal validation.
OwlReady2 uses SWRL to **infer** new data, which means that placing builtin functions in the consequent of a rule won't do anything.

For example the following rule...
```
Version(?v1), Version(?v2), VersionTransition(?vt),
  hasVersionMember(?vt, ?v1), hasVersionMember(?vt, ?v2),
  validTo(?v1, ?t1), validFrom(?v2, ?t2)
  -> lessThanOrEqualTo(?t1, ?t2)
```
Should be written like this:
```
Version(?v1), Version(?v2), VersionTransition(?vt),
  hasVersionMember(?vt, ?v1), hasVersionMember(?vt, ?v2),
  validTo(?v1, ?t1), validFrom(?v2, ?t2)
  -> BeforeOrIntersects(?t1, ?t2)
```

Then we can implement some script that will check all of the asserted temporal properties and make sure that they are valid.
