### ISSUE TITLE
How to handle edge 'tags' when converting to RDF

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Graph#7]
Considering [1, 2], and the current implementation of the differencegraph to CityGML 3, we may need an additional property to handle tags. Perhaps it is interesting to add it to the workspace ontology.

The current implementation uses `rdfs:comment`

[1] J. Samuel, S. Servigne, and G. Gesquière, “Representation of concurrent points of view of urban changes for city models,” J Geogr Syst, vol. 22, no. 3, pp. 335–359, Jul. 2020, doi: 10.1007/s10109-020-00319-1.
[2] V. Jaillot, “3D, temporal and documented cities : formalization, visualization and navigation,” Theses, Université de Lyon, 2020. [Online]. Available: https://tel.archives-ouvertes.fr/tel-03228436

**Comment by DiegoVinasco** [comment]
A comparison of typologies of existing temporal changes from [2] Table 2.2 :
| Renolen [Ren00] | De Luca et al. [DL+10] | Chaturvedi et al. [Cha+17] |
|-------------------|--------------------------|------------------------------|
| creation | creation | insert |
| alteration | modification | replace |
| destruction | demolition | delete |
| reincarnation | reconstruction |  |
| merging/annexation | union |  |
| splitting/deduction | division |  |
| reallocation |  |  |

[Ren00] Agnar Renolen. “Modelling the Real World: Conceptual Modelling in Spatiotemporal
Information System Design”. en. In: Transactions in GIS 4.1 (Jan. 2000),
pp. 23–42 (cit. on pp. 20–24, 37, 52).

[DL+10] Livio De Luca, Chawee Busarayat, Chiara Stefani, et al. “An iconography-based
modeling approach for the spatio-temporal analysis of architectural heritage”.
In: 2010 Shape Modeling International Conference. IEEE, 2010, pp. 78–89 (cit. on
pp. 22, 23).

[Cha+17] Kanishk Chaturvedi, Carl Stephen Smyth, Gilles Gesquière, Tatjana Kutzner,
and Thomas H. Kolbe. “Managing versions and history within semantic 3D city
models for the next generation of CityGML”. In: Advances in 3D Geoinformation.
Springer, 2017, pp. 191–206 (cit. on pp. 23–26, 31, 37, 38, 52).

**Comment by DiegoVinasco** [comment]
The following `tags` are produced by [3DUse's change detection](https://github.com/VCityTeam/3DUSE/blob/5d2f7d542447413f94424ba65a8125dcb20f7783/src/filters/ChangeDetection/ChangeDetectionDump.cpp#L356) algorithm :

tag | comment
--|--
unchanged | Unchanged building: same geometry, same (gml) ID.
re-ided | The building has been re-ided: same geometry, different (gml) ID
modified | The building geometry and ID have changed e.g. it was heightened; its footprint geometry changed, etc.
fused | reverse_correspondence_size_length > 1... It can be: <li> a split building that didn't work for both timestamps and which then denotes a logical fusion</li><li>a fusion or a split building problem + modifications</li><li>a split building problems + modifications</li>
subdivided | current building has more than one correspondent

**Comment by DiegoVinasco** [comment]
In addition tags are just defined as an array of strings however, it seems only one is ever used at a time

![taken from [2]](https://user-images.githubusercontent.com/23373264/145075988-8aba1088-d553-44ff-8b8e-ed11f8d73112.png)

**Comment by johnsamuelwrites** [comment]
We need to reflect on this case:

tag | comment
--|--
unchanged | Unchanged building: same geometry, same (gml) ID.

In the case of UD-Graph, unchanged should mean
tag | comment
--|--
unchanged | Unchanged building: same geometry, same (gml) ID, same semantic/thematic data

**Comment by johnsamuelwrites** [comment]
Another possible solution is to use SKOS CodeLists and handle different cases based on user requirements:
1. Using Renolen [Ren00]  
2. De Luca et al. [DL+10]
3. Chaturvedi et al. [Cha+17]
4. Tags for 3DUse's change detection algorithm 
5. Other user-defined lists

**Comment by DiegoVinasco** [comment]
Possible new sub-types of replacements:

| Subtype | Description |
|--|--|
| todo | re-ided + same semantic data |
| todo | re-ided + new/different semantic data |
| todo | modified + same semantic data |
| todo | modified + new/different semantic data |
| todo | same id + geometric changes + same semantic data |
| todo | same id + geometric changes + new/different semantic data |

**Comment by DiegoVinasco** [comment]
An skos ontology for representing 3D Use's transaction types/tags as a codelist [here](https://github.com/VCityTeam/UD-Graph/blob/master/Ontologies/Workspace/3.0/transactiontype.ttl)
